version: '3'
services:
  elasticsearch:
    container_name: con_elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0"
    ports:
      - 9200:9200
    networks:
      fhirfield_net:
        ipv4_address: 172.28.1.2
  testing:
    build: .
    ports:
      - 9090:8080
    environment:
      - ES_SERVER_HOST=172.28.1.2
      - ES_SERVER_PORT=9200
    links:
      - elasticsearch
    networks:
      fhirfield_net:
        ipv4_address: 172.28.1.3

networks:
  fhirfield_net:
    ipam:
      driver: bridge
      config:
      - subnet: 172.28.0.0/16

# https://docs.docker.com/compose/networking/
# https://blog.alejandrocelaya.com/2017/04/21/set-specific-ip-addresses-to-docker-containers-created-with-docker-compose/
